on: [push]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    
    - uses: azure/docker-login@v1
      with:
        login-server: consotobikes.azurecr.io
        username: ${{ secrets.acr_consotobikes_username }}
        password: ${{ secrets.acr_consotobikes_password }}
    
    - name: Build
      id: build-image
      run: |
        docker build "$GITHUB_WORKSPACE/" -f  "Dockerfile" -t consotobikes.azurecr.io/contosobikeaks:${{ github.sha }} --label dockerfile-path=Dockerfile
        
    - uses: Azure/container-scan@v0 
      name: Scan image for vulnerabilities
      id: container-scan
      continue-on-error: true
      with:
        image-name: consotobikes.azurecr.io/contosobikeaks:${{ github.sha }}      
     
    - name: Push
      id: push-image
      run: |
                docker push consotobikes.azurecr.io/contosobikeaks:${{ github.sha }}
                
    - name: Post logs to appinsights
      uses: Azure/publish-security-assessments@v0
      with: 
        scan-results-path: ${{ steps.container-scan.outputs.scan-report-path }}
        connection-string: ${{ secrets.AZ_APPINSIGHTS_CONNECTION_STRING }}
        subscription-token: ${{ secrets.AZ_SUBSCRIPTION_TOKEN }} 

    - uses: azure/k8s-set-context@v1
      with:
         kubeconfig: ${{ secrets.aks_contosobikeaks_kubeConfig }}
      id: login
    
    - name: Create namespace
      run: |
        namespacePresent=`kubectl get namespace | grep contosobikeaksdemo | wc -l`
        if [ $namespacePresent -eq 0 ]
        then
            echo `kubectl create namespace contosobikeaksdemo`
        fi

    - uses: azure/k8s-create-secret@v1
      with:
        namespace: contosobikeaksdemo
        container-registry-url: consotobikes.azurecr.io
        container-registry-username: ${{ secrets.acr_consotobikes_username }}
        container-registry-password: ${{ secrets.acr_consotobikes_password }}
        secret-name: contosobikeadockerauth
       
    - uses: azure/k8s-deploy@v1.2
      with:
        namespace: contosobikeaksdemo
        manifests: |
          manifests/deployment.yml
          manifests/service.yml
        images: |
          consotobikes.azurecr.io/contosobikeaks:${{ github.sha }}
        imagepullsecrets: |
          contosobikeadockerauth
